### ISSUE TITLE
The link to  Microsoft Interop Forms Toolkit 2.1 is dead

### ISSUE THREAD

**Issue by A9G-Data-Droid** [froque/interoptoolkitcs#1]
It looks like Microsoft took the download page down. I can't find it anywhere. Even if you search for it on the download site, the search comes up with hits but they all 404:

"We're sorry, this download is no longer available. "

**Comment by A9G-Data-Droid** [comment]
It can be found instead, in Archive.org. It would be good to make copies of it now while you can.

https://web.archive.org/web/20200810070025if_/https://download.microsoft.com/download/3/7/D/37D90824-1BE8-4085-920E-54812C045A55/InteropFormToolsInstaller.msi

**Comment by froque** [comment]
added in https://github.com/froque/interoptoolkitcs/commit/cb29d6f6e900c14656280c68a507d0655fcc342e
